[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: Proxy API calls to your backend in production by replacing BACKEND_URL
# [[redirects]]
#   from = "/api/*"
#   to = "https://YOUR-BACKEND-DOMAIN/api/:splat"
#   status = 200
#   force = true
